services:

  # Eureka Discovery
  discovery-service:
    image: palja/discovery-service:latest
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
    networks:
      - palja-network

  # API Gateway
  gateway-service:
    image: palja/gateway-service:latest
    container_name: gateway-service
    depends_on:
      - discovery-service
    ports:
      - "8080:8080"
    environment:
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
      ACCESS_SECRET_KEY: ${GATEWAY_ACCESS_SECRET_KEY}
    networks:
      - palja-network

  # 도메인 서비스
  payment-service:
    image: palja/payment-service:latest
    container_name: payment-service
    depends_on:
      - discovery-service
    ports:
      - "8081:8081"
    environment:
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
      TOSS_SECRET_KEY: ${TOSS_SECRET_KEY}
    networks:
      - palja-network

  review-service:
    image: palja/review-service:latest
    container_name: review-service
    depends_on:
      - discovery-service
    ports:
      - "8082:8082"
    environment:
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
    networks:
      - palja-network

  user-service:
    image: palja/user-service:latest
    container_name: user-service
    depends_on:
      - discovery-service
    ports:
      - "8083:8083"
    environment:
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
      ACCESS_SECRET_KEY: ${USER_ACCESS_SECRET_KEY}
      REFRESH_SECRET_KEY: ${USER_REFRESH_SECRET_KEY}
    networks:
      - palja-network

  product-service:
    image: palja/review-service:latest
    container_name: product-service
    depends_on:
      - discovery-service
    ports:
      - "8084:8084"
    environment:
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
    networks:
      - palja-network

  order-service:
    image: palja/review-service:latest
    container_name: order-service
    depends_on:
      - discovery-service
    ports:
      - "8085:8085"
    environment:
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
    networks:
      - palja-network

  coupon-service:
    image: palja/review-service:latest
    container_name: coupon-service
    depends_on:
      - discovery-service
    ports:
      - "8086:8086"
    environment:
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
    networks:
      - palja-network

  timedeal-service:
    image: palja/review-service:latest
    container_name: timedeal-service
    depends_on:
      - discovery-service
    ports:
      - "8087:8087"
    environment:
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
    networks:
      - palja-network

# 네트워크
networks:
  palja-network:
    driver: bridge