server:
  port: 8086

spring:
  application:
    name: coupon-service

  config:
    activate:
      on-profile: local

  profiles:
    include:
      - datasource
      - zipkin
      - redis
      - eureka
      - swagger
      - monitor
      - kafka