server:
  port: 8087

spring:
  application:
    name: timedeal-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: timedeal-service

  profiles:
    include:
      - datasource
      - zipkin
      - eureka
      - swagger
      - monitor