server:
  port: 8087

spring:
  application:
    name: timedeal-service

  config:
    activate:
      on-profile: prod

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: timedeal-service

  profiles:
    include:
      - datasource
      - zipkin
      - eureka
      - swagger
      - monitor