server:
  port: 8087

spring:
  application:
    name: timedeal-service
  kafka:
    bootstrap-servers: localhost:9092

  profiles:
    include:
      - datasource
      - zipkin
      - eureka
      - swagger
      - monitor