server:
  port: 8083

spring:
  application:
    name: user-service

  config:
    activate:
      on-profile: prod

  profiles:
    include:
      - datasource
      - zipkin
      - security
      - redis
      - eureka
      - swagger
      - monitor
      - kafka