server:
  port: 8085

spring:
  application:
    name: order-service

  config:
    activate:
      on-profile: prod

  profiles:
    include:
      - datasource
      - zipkin
      - swagger
      - eureka
      - monitor
      - kafka