server:
  port: 8084

spring:
  application:
    name: product-service

  config:
    activate:
      on-profile: local

  profiles:
    include:
      - datasource
      - zipkin
      - eureka
      - redis
      - swagger
      - monitor
      - kafka