CREATE SCHEMA IF NOT EXISTS palja_user      AUTHORIZATION paljagood;
CREATE SCHEMA IF NOT EXISTS palja_product   AUTHORIZATION paljagood;
CREATE SCHEMA IF NOT EXISTS palja_timedeal  AUTHORIZATION paljagood;
CREATE SCHEMA IF NOT EXISTS palja_coupon    AUTHORIZATION paljagood;
CREATE SCHEMA IF NOT EXISTS palja_order     AUTHORIZATION paljagood;
CREATE SCHEMA IF NOT EXISTS palja_payment   AUTHORIZATION paljagood;